name: CI
on: [push]
jobs:
  unit:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-python@v2
      - name: Install tools
        run: sudo apt-get install cmake clang
      - name: Build
        run: python script.py init --clang && python script.py build
      - name: === Unit test ===
        run: build/Release/main_test -s
  benchmark:
    name: Benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-python@v2
      - name: Install tools
        run: sudo apt-get install cmake clang
      - name: Build
        run: python script.py init --clang && python script.py build
      - name: === Benchmark ===
        run: build/Release/main_bench -s
